### ISSUE TITLE
Move custom component assignment to the config

### ISSUE THREAD

**Issue by FrederikBornemann** [marvin-schl/cs-fmu-mapper#19]
Currently, the custom components are assigned in an extern `main.py`, e.g.:

```python
custom_components = {
        "Algorithm": (
            f"ProjectPath.algorithms.{params.algotype}",
            None,
        ),
        "Plotter": (
            "plotter",
            {
                "plot_folder": f"{params.plot_folder}/{params.model}/{params.connection}/{params.algotype}{f'/{params.scenario}' if params.scenario else ''}",
            },
        ),
    }
master = ComponentFactory().createComponents(
    config=config, custom_components=custom_components
)
```

To run the co-simulation solely from `main.py` of the `cs-fmu-mapper`, the custom components should instead be assigned in the configuration file like this:

```yaml
Components:
  # ...
  scenario: OutdoorTemperature
# ...
General:
  plot_folder: "Path/To/Plots"
# ...
Algorithm:
   algotype: default
# ... 
CustomComponents:
  Algorithm:
    path: {{ "ProjectPath.algorithms." + Algorithm.algotype }}
  Plotter:
    path: ProjectPath.plotter
    parameters:
      plot_folder: {{ General.plot_folder + "/" + Components.model + "/" + Components.connection + "/" + Algorithm.algotype  + "/" + Components.get(scenario, "") }}
```
